### ISSUE TITLE
Issue in Method "convert_contentbody_to_new_type"

### ISSUE THREAD

**Issue by yangyixizg** [pushrodtechnology/PythonConfluenceAPI#11]
I suppose "_service_put_request" should be replaced by "_service_post_request"?

**Comment by rpcope1** [comment]
Yeah, looks like that's probably the case.

**Comment by rpcope1** [comment]
So this should be fixed in 3d34d08. If you have the chance, can you verify that this change works on your end?

**Comment by yangyixizg** [comment]
Thx, it works now after correction.
